all:
  is_secure:   true

listUser:
  is_secure:   true
  credentials: [[user_list_view,user_list_edit]]

editUser:
  is_secure:   true
  credentials: user_list_edit
      
status:
  is_secure:   true
  credentials: user_list_edit

deleteUser:
  is_secure:   true
  credentials: user_list_edit
    
listActionsRemoveUser:
  is_secure:   true
  credentials: user_list_edit

listActionsUserStatus:
  is_secure:   true
  credentials: user_list_edit
  