passwordRequestSuccess:
  layout: layoutAuth

  stylesheets: [layoutAuth, -oneness/fixed]
  
passwordRequestMailSent:
  layout: layoutAuth

  stylesheets: [layoutAuth, -oneness/fixed]

regenerateSuccess:
  has_layout: false