rendering: ~
security:
  class: afGuardBasicSecurityFilter

cache:     ~
common:
  class: sfCommonFilter

parser_validation: 
  class: XmlParserValidationFilter

null_filter: 
  class: NullFilter

exception_catching:
  class: ExceptionCatchingFilter

execution: ~