rendering: ~

apiKey:
  enabled: false
  
security: ~
  
csrf:
 class: sfCSRFFilter
 param:
   secret: 1cf56bd447817ac5e951dd37cb1e31fe

cache:     ~
common:
  class: sfCommonFilter

parser_validation: 
  class: XmlParserValidationFilter

null_filter: 
  class: NullFilter

exception_catching:
  class: ExceptionCatchingFilter

execution: ~