menu:
  attributes:
    title: 'App Flower'
  main:
    dashboard:
      attributes:
        label: 'Dashboard page'
        icon: /images/famfamfam/house_go.png
        type: button
        handler: 'afApp.load("/logout", "page");'
links:
  dashboard:
    title: Home
    iconCls: ''
    url: /
