all:
  is_secure: off
  
eventCorr1:
  is_secure: on
  credentials: event_edit

eventCorr2:
  is_secure: on
  credentials: event_edit

eventCorr3:
  is_secure: on
  credentials: event_edit

eventCorr4:
  is_secure: on
  credentials: event_edit

eventCorr5:
  is_secure: on
  credentials: event_edit

supressor1:
  is_secure: on
  credentials: event_edit

supressor2:
  is_secure: on
  credentials: event_edit

supressor3:
  is_secure: on
  credentials: event_edit

supressor4:
  is_secure: on
  credentials: event_edit

response0:
  is_secure: on
  credentials: event_edit

response1:
  is_secure: on
  credentials: event_edit

response2:
  is_secure: on
  credentials: event_edit

response3:
  is_secure: on
  credentials: event_edit

response4:
  is_secure: on
  credentials: event_edit

response5:
  is_secure: on
  credentials: event_edit

response6:
  is_secure: on
  credentials: event_edit

response7:
  is_secure: on
  credentials: event_edit

nadeSignature1:
  is_secure: on
  credentials: event_edit

nadeSignature2:
  is_secure: on
  credentials: event_edit

nadeSignature3:
  is_secure: on
  credentials: event_edit

nadeSignature4:
  is_secure: on
  credentials: event_edit

nadeSignature5:
  is_secure: on
  credentials: event_edit

pdf1:
  is_secure: on
  credentials: report_edit
  
pdf2:
  is_secure: on
  credentials: report_edit

pdf3:
  is_secure: on
  credentials: report_edit

pdf4:
  is_secure: on
  credentials: report_edit

pdf5:
  is_secure: on
  credentials: report_edit

pdf6:
  is_secure: on
  credentials: report_edit

pdf7:
  is_secure: on
  credentials: report_edit

