all:
  is_secure:   true

list:
  is_secure:   true
  credentials: [[permission_view,permission_edit]]
    
delete:
  is_secure:   true
  credentials: permission_edit
    
edit:
  is_secure:   true
  credentials: permission_edit
  