all:
  is_secure:   true

list:
  is_secure:   true
  credentials: [[role_view,role_edit]]
  
index:
  is_secure:   true
  credentials: [[role_view,role_edit]]
    
delete:
  is_secure:   true
  credentials: role_edit
    
edit:
  is_secure:   true
  credentials: role_edit
  