<?php



/**
 * Skeleton subclass for performing query and update operations on the 'timezones' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.4 on:
 *
 * Mon Nov  8 18:56:51 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TimeZonesQuery extends BaseTimeZonesQuery {

} // TimeZonesQuery
