dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  studio:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        sqlite:%SF_LOG_DIR%/studio_sqlite.db

  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=appflower_studio;host=localhost
      username:   root
      password:   root
      encoding:   utf8
      persistent: true
      pooling:    true
