propel:
  _attributes :          { package: "plugins.sfGuardPlugin.lib.model" }
  sf_guard_user:
    _attributes:         { phpName: sfGuardUser }
    id:
      
propel:
  # User Management 
  ############################################################################## 
  sf_guard_user_profile:
    _attributes: { phpName: sfGuardUserProfile }
    user_id:        { type: integer, primaryKey: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
    timezones_id:               { type: integer, foreignTable: timezones, foreignReference: id, onDelete: cascade }
    first_name:     varchar(20)
    last_name:      varchar(20)
    job_title:      varchar(255)
    phone_mobile:   varchar(255)
    phone_office:   varchar(255)
    personal_body:  longvarchar
    image:          varchar(255)
    is_developer:   boolean
    widget_help_is_enabled:     { type: boolean, default: true }
    created_at:
    updated_at:
    
  ########################################################
  # - CHANGELOG by radu ---------------------------------#
  ########################################################
  changelog: 
    _attributes: 
      idMethod: native
    id: 
      type: INTEGER
      required: true
      autoIncrement: true
      primaryKey: true
    object_id: 
      type: INTEGER
      required: true
      default: 0
    object_name: 
      type: VARCHAR
      size: 255
      required: true
      default:
    ###object_change_type: -1=delete, 0=update, 1=new
    object_change_type:
      type: VARCHAR
      size: 2
      required: true
      default: 0      
    object_link: 
      type: VARCHAR
      size: 255
    module_name: 
      type: VARCHAR
      size: 255
      required: true
      default:
    changes: 
      type: LONGVARCHAR
      required: true
    user_commit_msg: 
      type: LONGVARCHAR
      required: true
    user_id: 
      type: INTEGER
      required: true
      default: 0
      foreignTable: sf_guard_user
      foreignReference: id
      onDelete: cascade
    updated_at: 
      type: TIMESTAMP
   
  timezones:
    _attributes:                { phpName: TimeZones }
    id:
    name:                       { type: varchar(128), index: true }
    offset:                     { type: integer }
    created_at:
    updated_at: