<?php


/**
 * This class adds structure of 'resource_attribute_version' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Apr 21 19:31:34 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfPropelVersionableBehaviorPlugin.lib.model.map
 */
class ResourceAttributeVersionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfPropelVersionableBehaviorPlugin.lib.model.map.ResourceAttributeVersionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ResourceAttributeVersionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ResourceAttributeVersionPeer::TABLE_NAME);
		$tMap->setPhpName('ResourceAttributeVersion');
		$tMap->setClassname('ResourceAttributeVersion');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('ATTRIBUTE_NAME', 'AttributeName', 'VARCHAR', true, 255);

		$tMap->addColumn('ATTRIBUTE_VALUE', 'AttributeValue', 'LONGVARCHAR', false, null);

	} // doBuild()

} // ResourceAttributeVersionMapBuilder
